name: code check
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.14.4
        uses: actions/setup-go@v1
        with:
          go-version: 1.14.4
        id: go